# Project:  Privatium™  |  File: apps/_lint/pass/PV308/pv308ok/app.toml
# Authors:  Gabriel Mongefranco (@gabrielmongefranco)
# Created:  2026-09-05  |  Modified: 2026-09-05
# Summary:  decimal_sum() and date() modifiers.

[app]
slug    = "pv308ok"
title   = "Lint PV308"
version = "1.0.0"
api     = 1
tier    = "lua"
