// Project:  Privatium™  |  File: crates/xtask/src/skill_reference.rs
// Authors:  Gabriel Mongefranco (@gabrielmongefranco)
// Created:  2026-09-05  |  Modified: 2026-09-05
// Summary:  `cargo xtask gen-skill-reference [--check]` (docs/skills.md §7, plan M12): the
//           reference/ files of every skill, written from the crate — the lint rule table,
//           the pv surface, the sandbox's removed names, the limits, the permissions and
//           their plain-language widenings, the framework prefixes, the reserved slugs,
//           the icon set — and from the spec, whose numbered sections are copied in
//           whole so a skill's "pinned reference" is the contract's own words at this
//           version. --check regenerates in memory and fails naming every file that
//           differs, is missing, or was not written by the generator.

use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use anyhow::{Context, Result};
use privatium_core::app::manifest::{
    ManifestError, Permissions, RESERVED_SLUGS, SUPPORTED_API, Tier,
};
use privatium_core::config::LuaConfig;
use privatium_core::lint::{Class, RULES, Rule, RuleId, css, spec_ref};
use privatium_core::lua::{GLOBALS_REMOVED, OS_REMOVED, SURFACE};
use privatium_core::wire::router::FRAMEWORK_PREFIXES;
use privatium_core::{PROTOCOL, icons};

const BANNER: &str = "<!-- Generated by `cargo xtask gen-skill-reference` from the crate and the spec. \
Do not edit: CI fails on drift (docs/skills.md §7). Regenerate after a change to spec/ or to \
the crate facts it cites. -->\n\n";

/// Generate, then write or compare.
pub fn run(root: &Path, check: bool) -> Result<bool> {
    let files = generate(root)?;
    if !check {
        for (path, content) in &files {
            let target = root.join(path);
            if let Some(parent) = target.parent() {
                fs::create_dir_all(parent)?;
            }
            fs::write(&target, content).with_context(|| format!("writing {path}"))?;
        }
        println!(
            "gen-skill-reference: wrote {} files under skills/*/reference/",
            files.len()
        );
        return Ok(true);
    }
    let mut drift = Vec::new();
    for (path, content) in &files {
        match fs::read_to_string(root.join(path)) {
            Ok(existing) if normalize(&existing) == *content => {}
            Ok(_) => drift.push(format!("{path}: differs from what the generator writes")),
            Err(_) => drift.push(format!("{path}: missing")),
        }
    }
    for path in crate::repo::files(root)? {
        if path.starts_with("skills/") && path.contains("/reference/") && !files.contains_key(&path)
        {
            drift.push(format!("{path}: not written by the generator"));
        }
    }
    if drift.is_empty() {
        println!(
            "gen-skill-reference: {} files match what the crate and the spec generate",
            files.len()
        );
        return Ok(true);
    }
    for line in &drift {
        eprintln!("gen-skill-reference: {line}");
    }
    eprintln!(
        "\ngen-skill-reference: {} files drifted. A change to spec/ or to the crate that is not \
         reflected in skills/ is an incomplete change (docs/skills.md §7): run \
         `cargo xtask gen-skill-reference` and commit the result.",
        drift.len()
    );
    Ok(false)
}

fn normalize(text: &str) -> String {
    text.strip_prefix('\u{feff}')
        .unwrap_or(text)
        .replace("\r\n", "\n")
}

/// Every generated file, by repository-relative path.
fn generate(root: &Path) -> Result<BTreeMap<String, String>> {
    let mut files: BTreeMap<String, String> = BTreeMap::new();
    let mut put = |skill: &str, name: &str, body: String| {
        files.insert(
            format!("skills/{skill}/reference/{name}"),
            format!("{BANNER}{body}"),
        );
    };

    // privatium-overview
    put(
        "privatium-overview",
        "lint-rules.md",
        lint_rules(RULES.iter()),
    );
    put("privatium-overview", "glossary.md", glossary(root)?);
    put(
        "privatium-overview",
        "decision-tree.md",
        format!(
            "# Tiers and modes\n\nFrom `spec/app-contract.md §1` and `§2`, the contract's own words.\n\n{}\n{}",
            section(root, "spec/app-contract.md", "1")?,
            section(root, "spec/app-contract.md", "2")?
        ),
    );

    // privatium-tier1-lua
    put("privatium-tier1-lua", "pv-api.md", pv_api(root)?);
    put(
        "privatium-tier1-lua",
        "lsp-syntax.md",
        format!(
            "# LSP templates\n\nFrom `spec/lua-api.md §4`, the contract's own words.\n\n{}",
            section(root, "spec/lua-api.md", "4")?
        ),
    );
    let tier1_rules: Vec<RuleId> = RULES
        .iter()
        .map(|r| r.id)
        .filter(|id| !matches!(id, RuleId::PV206 | RuleId::PV304))
        .collect();
    put(
        "privatium-tier1-lua",
        "anti-patterns.md",
        anti_patterns(root, "Tier 1", &tier1_rules)?,
    );

    // privatium-tier2-web
    put("privatium-tier2-web", "pv-js.md", pv_js(root)?);
    put(
        "privatium-tier2-web",
        "endpoints.md",
        format!(
            "# The data API\n\nFrom `spec/data-api.md`, the contract's own words.\n\n{}\n{}\n{}\n{}\n{}",
            section(root, "spec/data-api.md", "1")?,
            section(root, "spec/data-api.md", "2")?,
            section(root, "spec/data-api.md", "3")?,
            section(root, "spec/data-api.md", "4")?,
            section(root, "spec/data-api.md", "7")?
        ),
    );
    put("privatium-tier2-web", "permissions.md", permissions(root)?);
    let tier2_rules: Vec<RuleId> = RULES
        .iter()
        .map(|r| r.id)
        .filter(|id| {
            !matches!(
                id,
                RuleId::PV106
                    | RuleId::PV107
                    | RuleId::PV201
                    | RuleId::PV202
                    | RuleId::PV203
                    | RuleId::PV204
                    | RuleId::PV302
                    | RuleId::PV303
                    | RuleId::PV306
                    | RuleId::PV307
                    | RuleId::PV308
                    | RuleId::PV403
                    | RuleId::PV405
                    | RuleId::PV407
                    | RuleId::PV503
                    | RuleId::PV505
                    | RuleId::PV506
            )
        })
        .collect();
    put(
        "privatium-tier2-web",
        "anti-patterns.md",
        anti_patterns(root, "Tier 2", &tier2_rules)?,
    );

    // privatium-tier3-rust
    put("privatium-tier3-rust", "api.md", rust_api(root)?);

    // privatium-accessibility
    put("privatium-accessibility", "rules.md", accessibility(root)?);

    // privatium-security
    put("privatium-security", "rules.md", security(root)?);

    // privatium-games
    put(
        "privatium-games",
        "isolation.md",
        format!(
            "# Games, engines and cross-origin isolation\n\nFrom `docs/frameworks.md §5`, plus what the loader says when an app asks for isolation in host mode.\n\n{}\n## What the loader says\n\n```\n{}\n```\n",
            section(root, "docs/frameworks.md", "5")?,
            ManifestError::CrossOriginIsolatedInHostMode
        ),
    );

    // Every skill: an index of its reference files.
    let mut by_skill: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for path in files.keys() {
        let mut parts = path.split('/');
        let (_, skill, _, name) = (parts.next(), parts.next(), parts.next(), parts.next());
        if let (Some(skill), Some(name)) = (skill, name) {
            by_skill
                .entry(skill.to_owned())
                .or_default()
                .push(name.to_owned());
        }
    }
    for (skill, names) in by_skill {
        let list: String = names.iter().map(|n| format!("- `{n}`\n")).collect();
        files.insert(
            format!("skills/{skill}/reference/README.md"),
            format!(
                "{BANNER}# Reference\n\nThe pinned reference for `{skill}` (docs/skills.md §3): generated from \
                 `privatium-core` {} (`{PROTOCOL}`, `api = {SUPPORTED_API}`) and the specification at the \
                 same commit, so what is written here is what this version implements.\n\n{list}\n\
                 Regenerate with `cargo xtask gen-skill-reference`; `--check` is the CI gate.\n",
                env!("CARGO_PKG_VERSION")
            ),
        );
    }
    Ok(files)
}

/// The numbered section of a spec document, heading included, up to the next heading of
/// the same or a higher level.
fn section(root: &Path, path: &str, number: &str) -> Result<String> {
    let text = crate::repo::read_normalized(&root.join(path))?;
    let lines: Vec<&str> = text.lines().collect();
    let start = lines
        .iter()
        .position(|line| line.starts_with('#') && spec_ref::heading_is(line, number))
        .with_context(|| format!("{path}: no heading numbered §{number}"))?;
    let level = lines[start].chars().take_while(|c| *c == '#').count();
    let mut end = lines.len();
    for (i, line) in lines.iter().enumerate().skip(start + 1) {
        let this = line.chars().take_while(|c| *c == '#').count();
        if this > 0 && this <= level && line[this..].starts_with(' ') {
            end = i;
            break;
        }
    }
    let mut body = lines[start..end].join("\n");
    while body.ends_with("\n---") || body.ends_with('\n') {
        body = body.trim_end_matches("---").trim_end().to_owned();
    }
    Ok(format!("{body}\n"))
}

fn escape_cell(text: &str) -> String {
    text.replace('|', "\\|")
}

fn rules_table<'a>(rules: impl Iterator<Item = &'a Rule>, criteria: bool) -> String {
    let mut out = String::new();
    if criteria {
        out.push_str(
            "| ID | Severity | Rule | WCAG 2.2 | Reads | Spec |\n|---|---|---|---|---|---|\n",
        );
    } else {
        out.push_str("| ID | Severity | Rule | Reads | Spec |\n|---|---|---|---|---|\n");
    }
    for rule in rules {
        if criteria {
            out.push_str(&format!(
                "| `{}` | {} | {} | {} | {} | `{}` |\n",
                rule.id,
                rule.severity,
                escape_cell(rule.title),
                rule.criterion.unwrap_or("—"),
                escape_cell(rule.reads),
                rule.spec
            ));
        } else {
            out.push_str(&format!(
                "| `{}` | {} | {} | {} | `{}` |\n",
                rule.id,
                rule.severity,
                escape_cell(rule.title),
                escape_cell(rule.reads),
                rule.spec
            ));
        }
    }
    out
}

fn lint_rules<'a>(rules: impl Iterator<Item = &'a Rule> + Clone) -> String {
    let mut out = String::from(
        "# Lint rules\n\nThe rule table of `privatium lint` as the crate holds it — `spec/cli.md §5.1`'s \
         rules with their stable IDs, severities, what the linter reads for each, and the section \
         every finding cites. `privatium lint apps/<slug>` exits 3 on findings; `--format json` \
         writes one object per finding with `id`, `severity`, `file`, `line`, `message`, `fix` and \
         `spec` (`§5.2`); `--severity error|warn|info` is the floor; `--fix` applies the mechanical \
         corrections of `§5.3` — a literal mount path to `url()`, `focusable=\"false\"` on an inline icon \
         — and nothing else.\n\n",
    );
    for class in [
        Class::Contract,
        Class::Security,
        Class::Correctness,
        Class::Accessibility,
        Class::Portability,
    ] {
        out.push_str(&format!("## {}\n\n", class.as_str()));
        out.push_str(&rules_table(
            rules.clone().filter(|r| r.class == class),
            class == Class::Accessibility,
        ));
        out.push('\n');
    }
    out
}

fn glossary(root: &Path) -> Result<String> {
    let slugs: String = RESERVED_SLUGS
        .iter()
        .map(|s| format!("`{s}`"))
        .collect::<Vec<_>>()
        .join(", ");
    let prefixes: String = FRAMEWORK_PREFIXES
        .iter()
        .map(|p| format!("`{p}`"))
        .collect::<Vec<_>>()
        .join(", ");
    Ok(format!(
        "# Glossary\n\n{}\n## Facts from the crate\n\n\
         | Fact | Value |\n|---|---|\n\
         | Protocol | `{PROTOCOL}` |\n\
         | App contract | `api = {SUPPORTED_API}` |\n\
         | Reserved slugs | {slugs} |\n\
         | Framework route prefixes (shadow a solo app's routes) | {prefixes} |\n\
         | Bootstrap Icons | {} ({} icons) |\n\
         | Tiers | {} |\n",
        section(root, "spec/protocol.md", "1")?,
        icons::version(),
        icons::count(),
        [Tier::Lua, Tier::Web, Tier::Rust]
            .iter()
            .map(|t| format!(
                "`{t}`{}",
                t.required_file()
                    .map_or(String::new(), |f| format!(" (requires `{f}`)"))
            ))
            .collect::<Vec<_>>()
            .join(", ")
    ))
}

fn pv_api(root: &Path) -> Result<String> {
    let mut surface = String::from("| Function | Section |\n|---|---|\n");
    for (name, section) in SURFACE {
        surface.push_str(&format!("| `pv.{name}` | `spec/lua-api.md §{section}` |\n"));
    }
    let limits = LuaConfig::default();
    let removed_os: String = OS_REMOVED
        .iter()
        .map(|n| format!("`os.{n}`"))
        .collect::<Vec<_>>()
        .join(", ");
    let removed_globals: String = GLOBALS_REMOVED
        .iter()
        .map(|n| format!("`{n}`"))
        .collect::<Vec<_>>()
        .join(", ");
    Ok(format!(
        "# The `pv` module\n\n## The surface, as the host registers it\n\nEvery `pv.<name>` the host \
         installs, from the crate; a name not here does not exist, whatever a search engine says. \
         `url`, `icon`, `fmt.*` and `t` are also sandbox globals (`§4.0`); `render`, `layout` and \
         `csrf` are template-only (`§4.1`).\n\n{surface}\n{}\n{}\n## The sandbox, as the host builds it\n\n\
         Removed: `io`, `debug`, `package.loadlib`, `package.cpath`, {removed_globals}, and {removed_os}. \
         Retained: `os.time`, `os.date`, `os.clock`, `string`, `table`, `math`, `coroutine`, `utf8`. \
         `require` reaches `'privatium'` and the app's own `lib/`.\n\n\
         | Limit | Default | Setting |\n|---|---|---|\n\
         | Instructions per request | {} | `lua.max_instructions` |\n\
         | Memory per VM | {} MB | `lua.max_memory_mb` |\n\
         | Wall clock per request | {} s | `lua.max_seconds` |\n\
         | VM pool size | CPU count | `lua.pool_size` |\n",
        section(root, "spec/lua-api.md", "3")?,
        section(root, "spec/lua-api.md", "5")?,
        limits.max_instructions,
        limits.max_memory_mb,
        limits.max_seconds,
    ))
}

/// The names `export const pv = { … }` in pv.js carries.
fn pv_js_exports(root: &Path) -> Result<Vec<String>> {
    let text =
        crate::repo::read_normalized(&root.join("crates/privatium-core/assets/shell/pv.js"))?;
    let start = text
        .find("export const pv = {")
        .context("pv.js: no `export const pv = {`")?;
    let block = &text[start..];
    let end = block
        .find("\n};")
        .context("pv.js: the export never closes")?;
    let mut names = Vec::new();
    for line in block[..end].lines().skip(1) {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        let ident = |s: &str| -> String {
            s.trim_start()
                .chars()
                .take_while(|c| c.is_ascii_alphanumeric() || *c == '_')
                .collect()
        };
        if let Some(rest) = line.strip_prefix("get ") {
            names.push(ident(rest));
        } else if !line.contains(':') && !line.contains('(') && !line.contains("=>") {
            names.extend(line.split(',').map(ident).filter(|n| !n.is_empty()));
        } else {
            names.push(ident(line));
        }
    }
    names.retain(|n| !n.is_empty());
    Ok(names)
}

fn pv_js(root: &Path) -> Result<String> {
    let names = pv_js_exports(root)?;
    let list: String = names
        .iter()
        .map(|n| format!("`pv.{n}`"))
        .collect::<Vec<_>>()
        .join(", ");
    Ok(format!(
        "# The `pv.js` helper\n\n## The surface, as the file exports it\n\n{list}\n\n\
         From `crates/privatium-core/assets/shell/pv.js`, served at `/static/pv.js`; a name not here \
         does not exist.\n\n{}\n{}",
        section(root, "spec/data-api.md", "5")?,
        section(root, "spec/data-api.md", "6")?
    ))
}

fn permissions(root: &Path) -> Result<String> {
    let cases: [(&str, Permissions); 6] = [
        (
            "inline_script = true",
            Permissions {
                inline_script: true,
                ..Permissions::default()
            },
        ),
        (
            "wasm = true",
            Permissions {
                wasm: true,
                ..Permissions::default()
            },
        ),
        (
            "eval = true",
            Permissions {
                eval: true,
                ..Permissions::default()
            },
        ),
        (
            "remote = [\"https://example.com\"]",
            Permissions {
                remote: vec!["https://example.com".into()],
                ..Permissions::default()
            },
        ),
        (
            "sql = true",
            Permissions {
                sql: true,
                ..Permissions::default()
            },
        ),
        (
            "cross_origin_isolated = true",
            Permissions {
                cross_origin_isolated: true,
                ..Permissions::default()
            },
        ),
    ];
    let mut table =
        String::from("| `[permissions]` | What the owner is told at install |\n|---|---|\n");
    for (key, permissions) in &cases {
        for widening in permissions.widenings() {
            table.push_str(&format!(
                "| `{key}` | {} |\n",
                escape_cell(&widening.to_string())
            ));
        }
    }
    let refusals = format!(
        "- `{}`\n- `{}`\n",
        ManifestError::CrossOriginIsolatedInHostMode,
        ManifestError::RemoteNotOrigin {
            entry: "https://example.com/path".into()
        }
    );
    Ok(format!(
        "# Permissions\n\n{}\n## What each widening says to the owner\n\nFrom the crate: the plain-language \
         line `spec/app-contract.md §5.4` requires at install, exactly as the loader words it.\n\n{table}\n\
         ## What the loader refuses\n\n{refusals}",
        section(root, "spec/app-contract.md", "5.4")?
    ))
}

fn rust_api(root: &Path) -> Result<String> {
    let text = crate::repo::read_normalized(&root.join("crates/privatium-core/src/lib.rs"))?;
    let start = text
        .find("\nimpl Node {")
        .context("lib.rs: no `impl Node`")?;
    let block = &text[start + 1..];
    let end = block
        .find("\n}\n")
        .context("lib.rs: `impl Node` never closes")?;
    let mut signatures = Vec::new();
    let mut current: Option<String> = None;
    for line in block[..end].lines() {
        if let Some(sig) = current.as_mut() {
            sig.push(' ');
            sig.push_str(line.trim());
            if line.trim_end().ends_with('{') {
                signatures.push(sig.trim_end_matches('{').trim().to_owned());
                current = None;
            }
        } else if line.trim_start().starts_with("pub fn ") {
            let sig = line.trim().to_owned();
            if sig.ends_with('{') {
                signatures.push(sig.trim_end_matches('{').trim().to_owned());
            } else {
                current = Some(sig);
            }
        }
    }
    let list: String = signatures.iter().map(|s| format!("{s}\n")).collect();
    Ok(format!(
        "# `privatium-core` as a library\n\n{}\n{}\n## `Node`'s public methods at this version\n\n\
         From `crates/privatium-core/src/lib.rs`. Phase 1 has no discovery, pairing or sync; those \
         arrive as typed methods in later phases and are absent here rather than stubbed.\n\n```rust\n{list}```\n",
        section(root, "spec/app-contract.md", "2.3")?,
        section(root, "spec/app-contract.md", "6")?
    ))
}

fn accessibility(root: &Path) -> Result<String> {
    let css_text =
        crate::repo::read_normalized(&root.join("crates/privatium-core/assets/shell/shell.css"))?;
    let schemes = css::root_tokens(&css_text);
    let pairs: [(&str, &str, f64); 16] = [
        ("--pv-fg", "--pv-bg", 4.5),
        ("--pv-fg", "--pv-panel", 4.5),
        ("--pv-fg", "--pv-line", 4.5),
        ("--pv-muted", "--pv-bg", 4.5),
        ("--pv-muted", "--pv-panel", 4.5),
        ("--pv-accent-fg", "--pv-accent", 4.5),
        ("--pv-warn-fg", "--pv-warn-bg", 4.5),
        ("--pv-alert-fg", "--pv-alert-bg", 4.5),
        ("--pv-ok-fg", "--pv-ok-bg", 4.5),
        ("--pv-focus", "--pv-bg", 3.0),
        ("--pv-focus", "--pv-panel", 3.0),
        ("--pv-accent", "--pv-bg", 3.0),
        ("--pv-accent", "--pv-panel", 3.0),
        ("--pv-alert-fg", "--pv-bg", 3.0),
        ("--pv-muted", "--pv-bg", 3.0),
        ("--pv-muted", "--pv-panel", 3.0),
    ];
    let mut table = String::from("| Pair | Floor | Light | Dark |\n|---|---|---|---|\n");
    for (fg, bg, floor) in pairs {
        let ratio = |scheme: usize| -> String {
            schemes
                .get(scheme)
                .and_then(|tokens| Some((tokens.get(fg)?, tokens.get(bg)?)))
                .and_then(|(a, b)| css::contrast(a, b))
                .map_or("—".into(), |r| format!("{r:.2}:1"))
        };
        table.push_str(&format!(
            "| `{fg}` on `{bg}` | {floor}:1 | {} | {} |\n",
            ratio(0),
            ratio(1)
        ));
    }
    Ok(format!(
        "# Accessibility rules\n\nThe `PV4xx` rules of `spec/cli.md §5.1` with the WCAG 2.2 success \
         criterion each enforces, from the crate. The linter judges templates and a Tier 2 document; \
         the framework's own pages are held to the same rules by its test suite over their rendered \
         HTML (`spec/cli.md §5.4`).\n\n{}\n## The framework's colour tokens\n\nFrom `shell.css` at \
         this version, both schemes, computed with the linter's contrast maths. An app that keeps \
         to these tokens inherits the floors.\n\n{table}",
        rules_table(
            RULES.iter().filter(|r| r.class == Class::Accessibility),
            true
        )
    ))
}

fn security(root: &Path) -> Result<String> {
    let removed_os: String = OS_REMOVED
        .iter()
        .map(|n| format!("`os.{n}`"))
        .collect::<Vec<_>>()
        .join(", ");
    let removed_globals: String = GLOBALS_REMOVED
        .iter()
        .map(|n| format!("`{n}`"))
        .collect::<Vec<_>>()
        .join(", ");
    Ok(format!(
        "# Security rules\n\nThe `PV2xx` rules of `spec/cli.md §5.1`, from the crate.\n\n{}\n\
         ## The Lua sandbox, as the host builds it\n\nRemoved: `io`, `debug`, `package.loadlib`, \
         `package.cpath`, {removed_globals}, and {removed_os}.\n\n{}\n{}",
        rules_table(RULES.iter().filter(|r| r.class == Class::Security), false),
        section(root, "spec/app-contract.md", "7")?,
        section(root, "spec/app-contract.md", "5.4")?
    ))
}

/// Which file of a fixture shows the rule. First existing wins.
fn primary_files(id: RuleId) -> &'static [&'static str] {
    match id {
        RuleId::PV101
        | RuleId::PV102
        | RuleId::PV103
        | RuleId::PV104
        | RuleId::PV105
        | RuleId::PV205
        | RuleId::PV501
        | RuleId::PV502
        | RuleId::PV503 => &["app.toml"],
        RuleId::PV106 | RuleId::PV107 => &["schema.sql"],
        RuleId::PV208 => &["sample/seed.jsonl"],
        RuleId::PV202
        | RuleId::PV204
        | RuleId::PV401
        | RuleId::PV402
        | RuleId::PV403
        | RuleId::PV405
        | RuleId::PV407 => &["views/index.lsp"],
        RuleId::PV404 => &["views/index.lsp", "views/_board.lsp"],
        RuleId::PV406 => &["static/app.css"],
        RuleId::PV206 | RuleId::PV207 | RuleId::PV304 => &["web/app.js"],
        RuleId::PV504 => &["web/index.html", "web/app.js"],
        _ => &["app.lua"],
    }
}

fn fence_language(path: &str) -> &'static str {
    match path.rsplit_once('.').map(|(_, ext)| ext) {
        Some("lua") => "lua",
        Some("sql") => "sql",
        Some("lsp" | "html") => "html",
        Some("toml") => "toml",
        Some("js") => "js",
        Some("css") => "css",
        Some("jsonl") => "json",
        _ => "",
    }
}

/// The file without its header block.
fn strip_header(path: &str, text: &str) -> String {
    let text = normalize(text);
    if path.ends_with(".lsp") {
        if let Some(end) = text.find("--?>") {
            return text[end + 4..].trim_start_matches('\n').to_owned();
        }
        return text;
    }
    if path.ends_with(".css") {
        if let Some(end) = text.find("*/") {
            return text[end + 2..].trim_start_matches('\n').to_owned();
        }
        return text;
    }
    let prefix = match path.rsplit_once('.').map(|(_, ext)| ext) {
        Some("lua" | "sql") => "--",
        Some("js") => "//",
        Some("toml") => "#",
        _ => return text,
    };
    let mut lines = text.lines().peekable();
    while lines.peek().is_some_and(|l| l.starts_with(prefix)) {
        lines.next();
    }
    let rest: Vec<&str> = lines.collect();
    rest.join("\n").trim_start_matches('\n').to_owned() + "\n"
}

/// The app folder of a fixture.
fn fixture_app(root: &Path, kind: &str, id: RuleId) -> Result<std::path::PathBuf> {
    let dir = root.join("apps").join("_lint").join(kind).join(id.as_str());
    let mut apps: Vec<_> = fs::read_dir(&dir)
        .with_context(|| format!("{}: no {kind} fixture", dir.display()))?
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.join("app.toml").is_file())
        .collect();
    apps.sort();
    apps.into_iter()
        .next()
        .with_context(|| format!("{}: holds no app", dir.display()))
}

fn anti_patterns(root: &Path, tier: &str, ids: &[RuleId]) -> Result<String> {
    let mut out = format!(
        "# Anti-patterns — {tier}\n\nWrong code beside right code (docs/skills.md §3), from the \
         linter's own corpus under `apps/_lint/`: for each rule the file that fails it and the file \
         that passes it, headers stripped. `privatium lint` reports the left column and accepts the \
         right.\n\n"
    );
    for id in ids {
        let rule = privatium_core::lint::rule(*id);
        let fail = fixture_app(root, "fail", *id)?;
        let pass = fixture_app(root, "pass", *id)?;
        let pick = |app: &Path| -> Option<(String, String)> {
            primary_files(*id).iter().find_map(|rel| {
                let path = app.join(rel);
                fs::read_to_string(&path).ok().map(|text| {
                    let shown = path
                        .strip_prefix(root)
                        .map(|p| p.to_string_lossy().replace('\\', "/"))
                        .unwrap_or_default();
                    (shown, strip_header(rel, &text))
                })
            })
        };
        let (fail_path, fail_text) = pick(&fail)
            .with_context(|| format!("{}: no primary file for {}", fail.display(), id))?;
        let (pass_path, pass_text) = pick(&pass)
            .with_context(|| format!("{}: no primary file for {}", pass.display(), id))?;
        out.push_str(&format!(
            "## `{id}` — {}\n\n{} · `{}`\n\n**Wrong** (`{fail_path}`):\n\n```{}\n{}```\n\n**Right** (`{pass_path}`):\n\n```{}\n{}```\n\n",
            escape_cell(rule.title),
            rule.severity,
            rule.spec,
            fence_language(&fail_path),
            fail_text,
            fence_language(&pass_path),
            pass_text,
        ));
    }
    Ok(out)
}
